name: CI

on:
  push:
    branches: [ 'main, 'v[0-9]+.[0-9x]+.[0-9x]+*'' ]
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9x]+.[0-9x]+*' ]

env:
  FLUTTER_CHANNEL: beta
  JAVA_VERSION: 12.x

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        test_type: [ static, unit ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}

    - uses: subosito/flutter-action@v1
      with:
        channel: ${{ env.FLUTTER_CHANNEL }}

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze
      if: matrix.test_type == 'static'
      uses: zgosalvez/github-actions-analyze-flutter@v1
      with:
        working-directory: lib
        fail-on-warnings: true

    - name: Analyze
      if: matrix.test_type == 'static'
      uses: zgosalvez/github-actions-analyze-flutter@v1
      with:
        working-directory: test
        fail-on-warnings: true

    - name: Analyze
      if: matrix.test_type == 'static'
      uses: zgosalvez/github-actions-analyze-flutter@v1
      with:
        working-directory: example
        fail-on-warnings: true

    - name: Run ${{ matrix.test_type }} tests
      if: matrix.test_type != 'static'
      run: tool/ci test-${{ matrix.test_type }}

#     - name: Upload ${{ matrix.test_type }} tests coverage to Codecov
#       if: matrix.test_type != 'static'
#       uses: codecov/codecov-action@v1
#       with:
#         token: ${{ secrets.CODECOV_TOKEN }}
#         # We can't use coverage/*.lcov.info because is not supported. See:
#         # https://github.com/codecov/codecov-bash/pull/400
#         files: '*.lcov.info'
#         flags: type-${{ matrix.test_type }},flutter-${{ env.FLUTTER_CHANNEL }}

#     - name: Save coverage reports as artifacts
#       if: matrix.test_type != 'static'
#       uses: actions/upload-artifact@v2
#       with:
#         name: coverage-${{ matrix.test_type }}-flutter_${{ env.FLUTTER_CHANNEL }}
#         path: coverage/*.lcov.info

# # vim: set et sw=2 sts=2 :
